version: "3.9"

services:
  database:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=budget
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
